/**
 * Cross-library benchmark runner. Spawns ONE node process per library (isolation: no inline-cache
 * contamination, no koota Number.prototype patch bleed), collects each `BENCH_JSON` line, checks
 * checksum parity per scenario, and writes RESULTS.md (a generated table). The curated narrative
 * lives in ../../BENCHMARKS.md.
 *
 *   pnpm bench          # from bench/compare
 *   node run.mjs
 */

import { execFileSync } from "node:child_process";
import { readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { renderReport } from "./report.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const SCENARIOS = ["packed_5", "simple_iter", "frag_iter", "entity_cycle", "add_remove"];
const FRAMES = ["sim_frame", "spawn_reap_frame", "toggle_frame"]; // realistic system-pipeline flows
const EXTENSIONS = ["serialize", "random_access"]; // beyond the canonical suite; libs may omit
// Preferred display order; any other scenario files present are appended.
const ORDER = ["strata-ecs", "bitecs", "becsy", "miniplex", "koota"];

const present = readdirSync(join(HERE, "scenarios"))
  .filter((f) => f.endsWith(".ts"))
  .map((f) => f.replace(/\.ts$/, ""));
const libs = [...ORDER.filter((l) => present.includes(l)), ...present.filter((l) => !ORDER.includes(l))];

const NODE_FLAGS = ["--expose-gc", "--allow-natives-syntax"];
const data = {}; // lib -> parsed BENCH_JSON
let context = null;

for (const lib of libs) {
  process.stderr.write(`\n▶ benchmarking ${lib} …\n`);
  try {
    const stdout = execFileSync(
      "node",
      [...NODE_FLAGS, join(HERE, "harness.ts"), `./scenarios/${lib}.ts`],
      { cwd: HERE, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"], maxBuffer: 64 * 1024 * 1024 },
    );
    const line = stdout.split("\n").find((l) => l.startsWith("BENCH_JSON:"));
    if (!line) throw new Error("no BENCH_JSON line in output");
    const parsed = JSON.parse(line.slice("BENCH_JSON:".length));
    data[lib] = parsed;
    context ??= parsed.context;
  } catch (e) {
    process.stderr.write(`  ✗ ${lib} failed: ${e.message}\n`);
  }
}

// Index results: lib -> scenarioId -> { avg_ns, p75_ns, p99_ns, checksum }
const byLib = {};
for (const [lib, out] of Object.entries(data)) {
  byLib[lib] = {};
  for (const r of out.results) byLib[lib][r.id] = r;
}

const okLibs = libs.filter((l) => byLib[l]);
const fmtUs = (ns) => (ns == null ? "—" : (ns / 1000).toFixed(2));
const opsPerSec = (ns) => (ns == null ? "—" : Math.round(1e9 / ns).toLocaleString("en-US"));

// --- checksum parity (per scenario, across libraries that implement it) ---
const parity = {};
for (const sc of [...SCENARIOS, ...FRAMES, ...EXTENSIONS]) {
  const seen = new Map(); // checksum -> [libs]
  for (const lib of okLibs) {
    const r = byLib[lib][sc];
    if (!r || r.checksum == null) continue;
    const k = String(r.checksum);
    if (!seen.has(k)) seen.set(k, []);
    seen.get(k).push(lib);
  }
  parity[sc] = seen;
}

// --- build RESULTS.md ---
const L = [];
L.push("# Benchmark results (generated)\n");
L.push("Generated by `node run.mjs`. Curated analysis: see `../../BENCHMARKS.md`.\n");
if (context) {
  L.push(`**Environment:** ${context.cpu} · ${context.arch} · Node ${context.node} · mitata 1.0.34 ` + "(`--expose-gc --allow-natives-syntax`), one process per library.\n");
}
L.push(`**Libraries:** ${okLibs.map((l) => `${l} ${data[l].version}`).join(" · ")}\n`);

// time table (µs/op, lower is better)
L.push("\n## Time per operation — µs/op (lower is better)\n");
L.push(`| scenario | ${okLibs.join(" | ")} |`);
L.push(`|---|${okLibs.map(() => "---:").join("|")}|`);
for (const sc of SCENARIOS) {
  const cells = okLibs.map((lib) => {
    const r = byLib[lib][sc];
    return r ? fmtUs(r.avg_ns) : "—";
  });
  // bold the fastest implemented cell
  const times = okLibs.map((lib) => byLib[lib][sc]?.avg_ns).filter((x) => x != null);
  const best = times.length ? Math.min(...times) : null;
  const rendered = okLibs.map((lib) => {
    const r = byLib[lib][sc];
    if (!r) return "—";
    const s = fmtUs(r.avg_ns);
    return best != null && r.avg_ns === best ? `**${s}**` : s;
  });
  L.push(`| ${sc} | ${rendered.join(" | ")} |`);
}

// throughput table (ops/s, higher is better)
L.push("\n## Throughput — ops/s (higher is better)\n");
L.push(`| scenario | ${okLibs.join(" | ")} |`);
L.push(`|---|${okLibs.map(() => "---:").join("|")}|`);
for (const sc of SCENARIOS) {
  const cells = okLibs.map((lib) => {
    const r = byLib[lib][sc];
    return r ? opsPerSec(r.avg_ns) : "—";
  });
  L.push(`| ${sc} | ${cells.join(" | ")} |`);
}

// tail latency
L.push("\n## Tail latency p99 — µs/op\n");
L.push(`| scenario | ${okLibs.join(" | ")} |`);
L.push(`|---|${okLibs.map(() => "---:").join("|")}|`);
for (const sc of SCENARIOS) {
  const cells = okLibs.map((lib) => {
    const r = byLib[lib][sc];
    return r ? fmtUs(r.p99_ns) : "—";
  });
  L.push(`| ${sc} | ${cells.join(" | ")} |`);
}

// realistic frames (full system pipeline per op)
L.push("\n## Realistic frames — µs/op (a full frame through each library's system pipeline)\n");
L.push("`sim_frame` = 4 systems over a mixed world (exclusion + joins + raw column read/write). `spawn_reap_frame` = systems spawn then destroy entities in-frame. `toggle_frame` = a system adds then removes a component in-frame.\n");
L.push(`| scenario | ${okLibs.join(" | ")} |`);
L.push(`|---|${okLibs.map(() => "---:").join("|")}|`);
for (const fr of FRAMES) {
  const times = okLibs.map((lib) => byLib[lib][fr]?.avg_ns).filter((x) => x != null);
  const best = times.length ? Math.min(...times) : null;
  const rendered = okLibs.map((lib) => {
    const r = byLib[lib][fr];
    if (!r) return "N/A";
    const s = fmtUs(r.avg_ns);
    return best != null && r.avg_ns === best ? `**${s}**` : s;
  });
  L.push(`| ${fr} | ${rendered.join(" | ")} |`);
}

// extensions (beyond canonical; N/A where a library doesn't implement one)
L.push("\n## Extension scenarios — µs/op (beyond the canonical suite)\n");
L.push("`serialize` = whole-world save+load round-trip (strata-ecs built-in; rivals have no equivalent). `random_access` = read a component for 10k random entities by handle.\n");
L.push(`| scenario | ${okLibs.join(" | ")} |`);
L.push(`|---|${okLibs.map(() => "---:").join("|")}|`);
for (const ex of EXTENSIONS) {
  const times = okLibs.map((lib) => byLib[lib][ex]?.avg_ns).filter((x) => x != null);
  const best = times.length ? Math.min(...times) : null;
  const rendered = okLibs.map((lib) => {
    const r = byLib[lib][ex];
    if (!r) return "N/A";
    const s = fmtUs(r.avg_ns);
    return best != null && r.avg_ns === best ? `**${s}**` : s;
  });
  L.push(`| ${ex} | ${rendered.join(" | ")} |`);
}

// parity
L.push("\n## Checksum parity (proof of equal work)\n");
L.push("| scenario | checksum | libraries in agreement | mismatches |");
L.push("|---|---:|---|---|");
for (const sc of [...SCENARIOS, ...FRAMES, ...EXTENSIONS]) {
  const groups = [...parity[sc].entries()];
  if (groups.length === 0) {
    L.push(`| ${sc} | — | (none implemented) | |`);
    continue;
  }
  groups.sort((a, b) => b[1].length - a[1].length);
  const [mainSum, mainLibs] = groups[0];
  const mism = groups.slice(1).map(([cs, ls]) => `${ls.join(",")}=${cs}`).join("; ");
  L.push(`| ${sc} | ${mainSum} | ${mainLibs.join(", ")} | ${mism || "—"} |`);
}

const md = L.join("\n") + "\n";
writeFileSync(join(HERE, "RESULTS.md"), md);
process.stdout.write("\n" + md);

// Persist structured data + render the HTML report (charts).
const versions = {};
for (const l of okLibs) versions[l] = data[l].version;
const payload = { context, libs: okLibs, versions, byLib };
writeFileSync(join(HERE, "results.json"), JSON.stringify(payload, null, 2));
writeFileSync(join(HERE, "report.html"), renderReport(payload));
process.stderr.write("\nwrote RESULTS.md · results.json · report.html\n");

// warn on any parity mismatch
let mismatches = 0;
for (const sc of [...SCENARIOS, ...FRAMES, ...EXTENSIONS]) if (parity[sc].size > 1) mismatches++;
if (mismatches) process.stderr.write(`\n⚠ ${mismatches} scenario(s) have checksum mismatches — investigate before trusting those rows.\n`);
else process.stderr.write("\n✓ all implemented scenarios agree on checksums.\n");
