/**
 * Sync-path benchmark runner — what a peer pays to APPLY a remote edit, as the document grows.
 *
 * The cross-library suite (../compare) measures the ECS hot loop. This one measures the durable
 * sync seam, where the question is not "how fast" but "does the cost of one small edit scale with
 * total document size". A collaborative app dies on that growth law, not on a constant factor.
 *
 * Spawns ONE process per (variant × n) cell — see cell.mjs for why that isolation is mandatory —
 * and reports the cold rep separately from the warm ones so process-state dependence is visible.
 *
 *   pnpm bench:sync            # from the repo root
 *   node run.mjs               # from bench/sync
 *   node run.mjs --sizes 1000,10000 --reps 3
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { cpus, loadavg } from "node:os";

const HERE = dirname(fileURLToPath(import.meta.url));
const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i === -1 ? dflt : process.argv[i + 1];
};

const SIZES = String(arg("sizes", "1000,4000,10000,25000")).split(",").map(Number);
const REPS = Number(arg("reps", 5));
const VARIANTS = [
  ["bootstrap", "fresh joiner imports the whole room (one-time join cost)"],
  ["steady_pristine", "receiver holds the room, no local edits, applies ONE small remote edit"],
  ["steady_local", "…and has made its own edit — the real collaborative case"],
  ["local_commit", "a peer editing its OWN doc — no remote traffic; is local editing doc-sized too?"],
  ["bare_loro", "floor: plain loro applying the same delta, no strata in the path"],
];

const median = (xs) => {
  const s = xs.slice().sort((a, b) => a - b);
  return s.length % 2 ? s[(s.length - 1) / 2] : (s[s.length / 2 - 1] + s[s.length / 2]) / 2;
};

// Machine hygiene: this project has twice published numbers taken under load. Record it, always.
const load1 = loadavg()[0];
const cores = cpus().length;
const loaded = load1 > cores * 0.5;

const rows = [];
let meta = null;
for (const [variant] of VARIANTS) {
  for (const n of SIZES) {
    process.stderr.write(`▶ ${variant} n=${n} …\n`);
    let parsed;
    try {
      const stdout = execFileSync(
        "node",
        [join(HERE, "cell.mjs"), "--variant", variant, "--n", String(n), "--reps", String(REPS)],
        { cwd: HERE, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"], maxBuffer: 32 * 1024 * 1024 },
      );
      const line = stdout.split("\n").find((l) => l.startsWith("SYNC_JSON:"));
      if (!line) throw new Error("no SYNC_JSON line");
      parsed = JSON.parse(line.slice("SYNC_JSON:".length));
    } catch (e) {
      process.stderr.write(`  ✗ ${variant} n=${n} failed: ${e.message}\n`);
      continue;
    }
    meta ??= parsed;
    rows.push({
      variant,
      n: parsed.n,
      cold: parsed.ms[0],
      warm: median(parsed.ms.slice(1).length ? parsed.ms.slice(1) : parsed.ms),
      all: parsed.ms,
      verified: parsed.verified,
      reps: parsed.reps,
      deltaBytes: parsed.deltaBytes,
      snapshotBytes: parsed.snapshotBytes,
    });
  }
}

const f = (x) => (x == null ? "—" : x.toFixed(2));
const L = [];
L.push("# Sync-path benchmark (generated)\n");
L.push("What a peer pays to APPLY a remote edit as the document grows. Generated by `node run.mjs`.\n");
if (meta) {
  L.push(
    `**Environment:** Node ${meta.node} · strata-ecs ${meta.strata} · **loro-crdt ${meta.loro}** · ` +
      `${cores} cores · 1-min load avg **${load1.toFixed(1)}**${loaded ? " ⚠️ **LOADED — absolute ms are indicative only**" : ""} · ` +
      `one process per cell · ${REPS} reps.\n`,
  );
  L.push(`**Delta under test:** ${meta.deltaBytes} bytes (one component write on one entity).\n`);
}

L.push("\n## Cost per operation — ms (cold = first rep in a fresh process, warm = median of the rest)\n");
L.push("| variant | n | snapshot | cold ms | warm ms | ms per 1k entities (warm) |");
L.push("|---|---:|---:|---:|---:|---:|");
for (const r of rows) {
  L.push(
    `| ${r.variant} | ${r.n.toLocaleString("en-US")} | ${(r.snapshotBytes / 1e6).toFixed(2)} MB | ` +
      `${f(r.cold)} | ${f(r.warm)} | ${f((r.warm / r.n) * 1000)} |`,
  );
}

L.push("\n## THE GROWTH LAW — cost ratio vs size ratio (warm)\n");
L.push("For `steady_*` the delta is a fixed ~115 bytes, so an O(delta) implementation stays **1.00x**");
L.push("no matter how big the document gets. Tracking the size ratio means the cost is O(document).\n");
L.push("| variant | size step | size ratio | cost ratio | verdict |");
L.push("|---|---|---:|---:|---|");
for (const [variant] of VARIANTS) {
  const vr = rows.filter((r) => r.variant === variant);
  for (let i = 1; i < vr.length; i++) {
    const prev = vr[i - 1], cur = vr[i];
    const sizeX = cur.n / prev.n;
    const costX = cur.warm / prev.warm;
    const expected = variant === "bootstrap" ? sizeX : 1;
    const verdict =
      variant === "bootstrap"
        ? costX <= sizeX * 1.3
          ? "linear (expected)"
          : "SUPER-LINEAR"
        : costX < 1.3
          ? "flat — O(delta) ✅"
          : `scales with document ❌ (${costX.toFixed(1)}x for a fixed-size edit)`;
    L.push(
      `| ${variant} | ${prev.n.toLocaleString("en-US")}→${cur.n.toLocaleString("en-US")} | ` +
        `${sizeX.toFixed(1)}x | ${costX.toFixed(2)}x | ${verdict} (ideal ${expected.toFixed(2)}x) |`,
    );
  }
}

L.push("\n## Process-state sensitivity (cold vs warm within one process)\n");
L.push("A large spread here is why every cell gets its own process: sweeping sizes in one process");
L.push("lets an earlier small document make a later large one look fast.\n");
L.push("| variant | n | cold | warm | spread |");
L.push("|---|---:|---:|---:|---:|");
for (const r of rows) {
  const spread = r.warm > 0 ? r.cold / r.warm : 0;
  L.push(`| ${r.variant} | ${r.n.toLocaleString("en-US")} | ${f(r.cold)} | ${f(r.warm)} | ${spread.toFixed(1)}x |`);
}

L.push("\n## Convergence check\n");
L.push("Every rep asserts the remote edit is readable from the receiver's doc afterwards — a");
L.push("benchmark that timed a silently-dropped import would be worse than none.\n");
const bad = rows.filter((r) => r.verified !== r.reps);
const expectedCells = VARIANTS.length * SIZES.length;
if (rows.length !== expectedCells) {
  L.push(`**FAILED:** only ${rows.length}/${expectedCells} cells produced results — the rest errored.\n`);
} else {
  L.push(bad.length === 0 ? "All cells verified: every rep converged. ✅\n" : `**FAILED:** ${bad.map((r) => `${r.variant}/${r.n} (${r.verified}/${r.reps})`).join(", ")}\n`);
}

const md = L.join("\n") + "\n";
writeFileSync(join(HERE, "RESULTS.md"), md);
writeFileSync(join(HERE, "results.json"), JSON.stringify({ meta, load1, cores, rows }, null, 2));
process.stdout.write("\n" + md);
process.stderr.write("\nwrote RESULTS.md · results.json\n");

// A run that produced NO rows must never look like a pass — every cell erroring is the loudest
// possible failure, not a clean sheet.
if (rows.length !== expectedCells) {
  process.stderr.write(`\n✗ only ${rows.length}/${expectedCells} cells produced results.\n`);
  process.exit(1);
}
if (bad.length) {
  process.stderr.write("\n✗ convergence check FAILED — numbers are not meaningful.\n");
  process.exit(1);
}
